BI/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
]


urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"

urlpatterns = [

	path('',views.dashboard_setup, name = "dashboard-setup"),
	path('render/<str:slug>/',views.dashboard_render, name = "dashboard-render"),
	path('compute/',views.dashboard_compute_pred, name = "dashboard-compute-pred"),

]

dashboard/models.py
from django.db import models
from PIL import Image

class DataStore(models.Model):

	data = models.FileField(upload_to = "data/")
	date_added = models.DateField(auto_now_add = True)
	slug = models.SlugField(unique = True)
	name = models.CharField(max_length = 256)

	def __str__(self):
		return str(self.name)

dashboard/forms.py
from django import forms
from .models import DataStore

class DataForm(forms.ModelForm):
	class Meta:
		model = DataStore
		exclude = ('slug',)

dashboard/views.py
from django.shortcuts import render,redirect
from .models import DataStore
from .forms import DataForm

import datetime

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import math
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt

def dashboard_setup(request):
	
	avail_data = DataStore.objects.all().order_by('date_added')

	if request.method == 'POST':
		dataform = DataForm(request.POST,request.FILES)
		if(dataform.is_valid()):
			instance = dataform.save(commit = False)
			
			data_count = DataStore.objects.all().count()
			now = datetime.datetime.now().time()
			slug = 'data-'+str(data_count)+str(now)
			
			instance.slug = slug
			instance.save()

			return redirect('dashboard:dashboard-setup')

	else:
		dataform = DataForm()

	return render(request, 'dashboard/dashboard-setup.html', {'dataform':dataform,'avail_data':avail_data})

def dashboard_render(request,slug):

	data = DataStore.objects.get(slug=slug)

	df = pd.read_csv(data.data.path)
	df = df.drop(["id"],axis = 1)
	for index,row in df.iterrows():
		if(row['bedrooms']== 33):
			df = df.drop(index = index, axis = 1)

		inst = row['bathrooms']
		if(inst - int(inst)>= 0.5):
			inst = math.ceil(inst)
		else:
			inst = math.floor(inst)

		df.at[index,'bathrooms'] = inst
    
	df = df.dropna()
	count_row = df.shape[0]
	mean_price = round(df['price'].mean(),3)
	f,ax = plt.subplots(figsize=(20, 20))
	sns.heatmap(df.corr(), annot=True, linewidths=.2, fmt= '.3f',ax=ax).get_figure().savefig("static/heatmap.png")
	f,bx = plt.subplots(figsize=(15, 15))
	sns.lineplot(x="floors", y="price", data=df,ax=bx).get_figure().savefig("static/floors-price.png")
	fig_dims = (15, 10)
	fig, ax = plt.subplots(figsize=fig_dims)
	
	sns.barplot(x="grade", y="price", data=df,ax=ax).get_figure().savefig("static/grade-price.png")
	sns.barplot(x="condition", y="price", data=df,ax=ax).get_figure().savefig("static/condition-price.png")
	sns.barplot(x="view", y="price", data=df,ax=ax).get_figure().savefig("static/view-price.png")
	sns.barplot(x="bedrooms", y="price", data=df,ax=ax).get_figure().savefig("static/bedrooms-price.png")
	sns.barplot(x="bathrooms", y="price", data=df,ax=ax).get_figure().savefig("static/bathrooms-price.png")


	y = df['price']

	drop_list = ['view', 'yr_renovated','waterfront','date', 'price','zipcode','lat','long'] 
	X1 = df.drop(drop_list,axis=1)

	X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y, test_size = 1/3, random_state = 43)

	
	reg = XGBRegressor(n_estimators=100,learning_rate=.2)
	reg.fit(X1_train,y1_train)
	reg_score = round(reg.score(X1_train,y1_train),3)
	pred = reg.predict(X1_test)

	reg_score = reg_score*100
	rms = round(sqrt(mean_squared_error(y1_test, pred)),3)

	#df_show = df.to_html(max_rows=10)
	
	brand = str(data) + ' Dashboard'

	return render(request,'dashboard/dashboard-render.html',{'brand':brand,'data':data,'count_row':count_row,'mean_price':mean_price,'reg_score':reg_score,'rms':rms})


def dashboard_compute_pred(request):

	if(request.method == 'POST' and 'bedrooms' in request.POST and 'bathrooms' in request.POST and 'floors' in request.POST and 'condition' in request.POST and 'grade' in request.POST and 'sqft_living' in request.POST and 'sqft_lot' in request.POST and 'sqft_above' in request.POST and 'sqft_basement' in request.POST and 'sqft_living15' in request.POST and 'sqft_lot15' in request.POST and 'yr_built' in request.POST and 'data' in request.POST):
		
		bedrooms = request.POST['bedrooms']
		bedrooms = int(bedrooms)
		bathrooms = request.POST['bathrooms']
		bathrooms = int(bathrooms)
		floors = request.POST['floors']
		floors = int(floors)
		condition = request.POST['condition']
		condition = int(condition)
		grade = request.POST['grade']
		grade = int(grade)
		sqft_living = request.POST['sqft_living']
		sqft_living = int(sqft_living)
		sqft_lot = request.POST['sqft_lot']
		sqft_lot = int(sqft_lot)
		sqft_above = request.POST['sqft_above']
		sqft_above = int(sqft_above)
		sqft_basement = request.POST['sqft_basement']
		sqft_basement = int(sqft_basement)
		sqft_living15 = request.POST['sqft_living15']
		sqft_living15 = int(sqft_living15)
		sqft_lot15 = request.POST['sqft_lot15']
		sqft_lot15 = int(sqft_lot15)
		yr_built = request.POST['yr_built']
		yr_built = int(yr_built)
		temp = request.POST['data']

		test = {'bedrooms':bedrooms,'bathrooms':bathrooms,'sqft_living':sqft_living,'sqft_lot':sqft_lot,'floors':floors,'condition':condition,'grade':grade,'sqft_above':sqft_above,'sqft_basement':sqft_basement,'yr_built':yr_built,'sqft_living15':sqft_living15,'sqft_lot15':sqft_lot15}
		df_test=pd.DataFrame(test,index=[0])

		
		data = DataStore.objects.get(slug=temp)

		df = pd.read_csv(data.data.path)
	

		df = df.drop(["id"],axis = 1)
		for index,row in df.iterrows():
			if(row['bedrooms']== 33):
				df = df.drop(index = index, axis = 1)

			inst = row['bathrooms']
			if(inst - int(inst)>= 0.5):
				inst = math.ceil(inst)
			else:
				inst = math.floor(inst)

			df.at[index,'bathrooms'] = inst
	    
		df = df.dropna()
		
		y = df['price']

		drop_list = ['view', 'yr_renovated','waterfront','date', 'price','zipcode','lat','long'] 
		X1 = df.drop(drop_list,axis=1)

		X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y, test_size = 1/3, random_state = 43)

		
		reg = XGBRegressor(n_estimators=100,learning_rate=.2)
		reg.fit(X1_train,y1_train)
		result_pred = reg.predict(df_test)
		result_pred = float(result_pred)

		brand = str(data) + ' Dashboard'

		return render(request,'dashboard/dashboard-compute-pred.html',{'brand':brand,'data':data,'result_pred':result_pred,'bedrooms':bedrooms,'bathrooms':bathrooms,'floors':floors,'condition':condition,'grade':grade,'sqft_living':sqft_living,'sqft_lot':sqft_lot,'sqft_above':sqft_above,'sqft_basement':sqft_basement,'sqft_living15':sqft_living15,'sqft_lot15':sqft_lot15,'yr_built':yr_built})

	

dashboard/templates/dashboard/dashboard-compute-pred.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
	<center>
		<h3>Model trained on  {{data}}</h3>	
		<br>
		<div class="col-md-5">
		<div class="card shadow p-3 mb-6">
			<div class="card-body">
				<h2 style="color:#6B8E23;">$ {{result_pred}}</h2>is the predicted price for the following data input<br>
				<hr>
				<b>bedrooms</b> = {{bedrooms}}<br>
				<b>bathrooms</b> = {{bathrooms}}<br>
				<b>floors</b> = {{floors}}<br>
				<b>condition</b> = {{condition}}<br>
				<b>grade</b> = {{grade}}<br>
				<b>sqft_living</b> = {{sqft_living}} sqft<br>
				<b>sqft_lot</b> = {{sqft_lot}} sqft<br>
				<b>sqft_above</b> = {{sqft_above}} sqft<br>
				<b>sqft_basement</b> = {{sqft_basement}} sqft<br>
				<b>sqft_living15</b> = {{sqft_living15}} sqft<br>
				<b>sqft_lot15</b> = {{sqft_lot15}}sqft<br>
				<b>yr_built</b> = {{yr_built}}<br>
			</div>
		</div>
		</div>
		<br>
		<a class="btn btn-outline-dark" href="{% url 'dashboard:dashboard-render' data.slug %}">Back to Dashboard</a>
	</center>
</div>
{% endblock %}

dashboard/templates/dashboard/dashboard-render.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
	<div class = "container-fluid">

		<div class="row">
			<div class="col-md-8">
				<div class="card shadow p-3 mb-5">
					<div class="card-body">
						<div class="row">
							<div class="col-md-3">
								<font size="6" color="orange">{{count_row}}</font><br><font size="4">Rows</font>
							</div>
							<div class="col-md-3">
								<font size="6" color="orange">{{mean_price}}</font><br><font size="4">Average Price</font>
							</div>
							<div class="col-md-3">
								<font size="6" color="orange">{{reg_score}}%</font><br><font size="4">Model Accurary</font>
							</div>
							<div class="col-md-3">
								<font size="6" color="orange">{{rms}}</font><br><font size="4">Root Mean Square Error</font>
							</div>
						</div>
						<hr>
						<div class="row">
							<div class="col-xl-3 xol-lg-3 col-md-6 col-sm-6">
								<center>
									<a href="{% static 'heatmap.png' %}" target="_blank"><img src="{% static 'heatmap.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>HeatMap
								</center>
								<br>
							</div>
							<div class="col-xl-3 xol-lg-3 col-md-6 col-sm-6">
								<center>
									<a href="{% static 'grade-price.png' %}" target="_blank"><img src="{% static 'grade-price.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>Grade vs Price
								</center>
								<br>
							</div>
							<div class="col-xl-3 xol-lg-3 col-md-6 col-sm-6">
								<center>
									<a href="{% static 'condition-price.png' %}" target="_blank"><img src="{% static 'condition-price.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>Condition vs Price
								</center>
								<br>
							</div>
							<div class="col-xl-3 xol-lg-3 col-md-6 col-sm-6">	
								<center>
									<a href="{% static 'view-price.png' %}" target="_blank"><img src="{% static 'view-price.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>View vs Price
								</center>
							</div>
							<div class="col-xl-4 xol-lg-4 col-md-6 col-sm-6">	
								<center>
									<a href="{% static 'bedrooms-price.png' %}" target="_blank"><img src="{% static 'bedrooms-price.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>Bedrooms vs Price
								</center>
							</div>
							<div class="col-xl-4 xol-lg-4 col-md-6 col-sm-6">	
								<center>
									<a href="{% static 'bathrooms-price.png' %}" target="_blank"><img src="{% static 'bathrooms-price.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>Bathrooms vs Price
								</center>
							</div>
							<div class="col-xl-4 xol-lg-4 col-md-6 col-sm-6">	
								<center>
									<a href="{% static 'floors-price.png' %}" target="_blank"><img src="{% static 'floors-price.png' %}" style="width:200px;height: 200px;" class="img-thumbnail"></a><br>Floors vs Price
								</center>
							</div>
						</div><br>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="card shadow p-3 mb-5">
					<div class="card-body">
						<center>
							<h4>Prediction Form</h4><br>
							<form class="form-group" method="POST" action="{% url 'dashboard:dashboard-compute-pred' %}"> 
								{% csrf_token %}
								<input type="number" name="bedrooms" class="form-control" placeholder="No.of Bedrooms - Range(2 - 11)">
								<input type="number" name="bathrooms" class="form-control" placeholder="No.of Bathrooms - Range(1 - 8)">
								<input type="number" name="floors" class="form-control" placeholder="No.of Floors - Range(1 - 4)">
								<input type="number" name="condition" class="form-control" placeholder="Condition - Range(1 - 5)">
								<input type="number" name="grade" class="form-control" placeholder="Grade - Range(1 - 13)">
								<input type="number" name="sqft_living" class="form-control" placeholder="Living Space in sqft - Range(290 - 10540)">
								<input type="number" name="sqft_lot" class="form-control" placeholder="Lot Space in sqft - Range(651 - 11390)">
								<input type="number" name="sqft_above" class="form-control" placeholder="Living Space above in sqft - Range(290 - 9410)">
								<input type="number" name="sqft_basement" class="form-control" placeholder="Basement Space above in sqft - Range(0 - 4820)">
								<input type="number" name="sqft_living15" class="form-control" placeholder="Living Space of nearby in sqft - Range(399 - 6210)">
								<input type="number" name="sqft_lot15" class="form-control" placeholder="Lot Space of nearby in sqft - Range(651 - 11390)">
								<input type="number" name="yr_built" class="form-control" placeholder="Year built - Range(1900 - 2015)"><br>
								<input type="hidden" name="data" value={{data.slug}}>
								<input type="submit" name="Submit" value="Submit" class="btn btn-outline-success"><br>
							</form>
						</center>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

dashboard/templates/dashboard/dashboard-setup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

	<div class = "container">
		<div class="row">
			<div class="col-md-6">
				<h2>Add Data to Store</h2>
				<hr>
				<div class="card shadow p-3 mb-5">
					<div class="card-body">
						<form class="form-group" method="POST" action="{% url 'dashboard:dashboard-setup' %}" enctype="multipart/form-data">
							{% csrf_token %}
							{{dataform|crispy}}
							<input type="submit" name="Submit" value="Submit">
						</form>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<h2>Data In Store</h2>
				<hr>
				<div class="card shadow p-3 mb-5">
					<div class="card-body">
						<div class="row">
							{% for data in avail_data %}
							<div class="col-md-4">
								<b>{{data.name}}</b>
							</div>
							<div class="col-md-4">
								<small>{{data.date_added}}</small>
							</div>
							<div class="col-md-4">
								<a href="{% url 'dashboard:dashboard-render' data.slug %}" class="btn btn-outline-primary">Use Data</a>
							</div>
							<br><br>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/base.html
<!doctype html>
<!DOCTYPE html>
<html>
<head>

	<!--bootstrap4 CSS-->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

	<!--bootstrap4 JS-->
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	<!--fonts-->
	<link href="https://fonts.googleapis.com/css?family=Fredoka+One|Inter:300&display=swap" rel="stylesheet"> 

	<title>Housing Price Predicition</title>

</head>
<body style="background-color: #E0FFFF;">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'dashboard:dashboard-setup' %}">
	  	<img src="#" alt="logo" width="50" height="50" class="d-inline-block" alt="">&nbsp; {% if brand %}{{ brand }}{% else %} Housing Price Prediction {% endif %}
	  </a>
	</nav>
	<br>
	{% block content %}{% endblock %}
</body>
</html>